export enum IconName {
	Angular = 'angular',
	Cypress = 'cypress',
	Debian = 'debian',
	Django = 'django',
	Docker = 'docker',
	Eclipse = 'eclipse',
	Express = 'express',
	Figma = 'figma',
	Github = 'github',
	Gitlab = 'gitlab',
	Intellij = 'intellij',
	Java = 'java',
	Javacript = 'javascript',
	Jira = 'jira',
	Material = 'material',
	Node = 'node',
	Postgresql = 'postgresql',
	React = 'react',
	SCSS = 'scss',
	Spring = 'spring',
	Sqlserver = 'sqlserver',
	Typescript = 'typescript',
	Ubuntu = 'ubuntu',
	Vscode = 'vscode',
}